http:
  routers:
    frontend:
      entryPoints:
        - web
      service: frontend
      rule: PathPrefix(`/`)
    backend:
      entryPoints:
        - web
      service: backend
      rule: PathPrefix(`/ws`)

  services:
    frontend:
      loadBalancer:
        healthCheck:
          path: /index.html
          port: 5173
          interval: 1s
        servers:
          - url: http://localhost:5173/ # For linux and windows WSL
          - url: http://{{ env "HOSTNAME" }}:5173/ # For the windows host Machine
        passHostHeader: true

    backend:
      loadBalancer:
        healthCheck:
          path: /ping
          port: 8080
          interval: 1s
        servers:
          - url: http://localhost:8080/ # For linux and windows WSL
          - url: http://{{ env "HOSTNAME" }}:8080/ # For the windows host Machine
        passHostHeader: true
